import type { ThemeConfig } from 'antd'
import { theme as antdTheme } from 'antd'

export const COLORS = {
  bg: '#0a0a10',
  bgElevated: '#13131c',
  bgCard: '#1a1a26',
  bgInput: 'rgba(255,255,255,0.04)',
  border: 'rgba(255,255,255,0.08)',
  borderHover: 'rgba(255,255,255,0.16)',
  text: '#f5f5f7',
  textSecondary: '#a8a8b3',
  textMuted: '#6b6b78',
  primary: '#7c8cff',
  primaryHover: '#9aa6ff',
  primaryDark: '#5a6cf0',
  accent: '#c084fc',
  success: '#22c55e',
  warning: '#f59e0b',
  error: '#ef4444',
  gradient: 'linear-gradient(135deg, #7c8cff 0%, #c084fc 100%)',
  gradientSoft: 'linear-gradient(135deg, rgba(124,140,255,0.15) 0%, rgba(192,132,252,0.15) 100%)',
}

export const darkTheme: ThemeConfig = {
  algorithm: antdTheme.darkAlgorithm,
  token: {
    colorPrimary: COLORS.primary,
    colorSuccess: COLORS.success,
    colorWarning: COLORS.warning,
    colorError: COLORS.error,
    colorBgBase: COLORS.bg,
    colorBgContainer: COLORS.bgCard,
    colorBgElevated: COLORS.bgElevated,
    colorBgLayout: COLORS.bg,
    colorText: COLORS.text,
    colorTextSecondary: COLORS.textSecondary,
    colorTextTertiary: COLORS.textMuted,
    colorBorder: COLORS.border,
    colorBorderSecondary: COLORS.border,
    borderRadius: 12,
    borderRadiusLG: 16,
    borderRadiusSM: 8,
    fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", "Inter", "Segoe UI", Roboto, sans-serif',
    fontSize: 14,
    fontSizeLG: 16,
    fontSizeXL: 20,
    fontSizeHeading1: 32,
    fontSizeHeading2: 26,
    fontSizeHeading3: 20,
    fontSizeHeading4: 17,
    boxShadow: '0 8px 24px rgba(0,0,0,0.35)',
    boxShadowSecondary: '0 4px 12px rgba(0,0,0,0.25)',
    motionDurationMid: '0.2s',
    motionDurationSlow: '0.32s',
    wireframe: false,
  },
  components: {
    Button: {
      controlHeight: 42,
      controlHeightLG: 48,
      controlHeightSM: 32,
      borderRadius: 12,
      fontWeight: 600,
      primaryShadow: 'none',
      defaultShadow: 'none',
    },
    Input: {
      controlHeight: 44,
      controlHeightLG: 50,
      borderRadius: 12,
      activeBorderColor: COLORS.primary,
      hoverBorderColor: COLORS.borderHover,
    },
    Card: {
      borderRadiusLG: 16,
      paddingLG: 20,
      colorBgContainer: COLORS.bgCard,
      colorBorderSecondary: COLORS.border,
    },
    Modal: {
      contentBg: COLORS.bgElevated,
      headerBg: COLORS.bgElevated,
      borderRadiusLG: 20,
    },
    Drawer: {
      colorBgElevated: COLORS.bgElevated,
    },
    Tag: {
      borderRadiusSM: 999,
      defaultBg: 'rgba(255,255,255,0.06)',
      defaultColor: COLORS.textSecondary,
    },
    Tabs: {
      itemSelectedColor: COLORS.primary,
      itemHoverColor: COLORS.primaryHover,
      inkBarColor: COLORS.primary,
    },
    Segmented: {
      itemSelectedBg: COLORS.gradientSoft,
      itemSelectedColor: COLORS.text,
      itemHoverBg: 'rgba(255,255,255,0.06)',
      trackBg: 'rgba(255,255,255,0.04)',
    },
    Menu: {
      itemBg: 'transparent',
      itemSelectedBg: 'rgba(124,140,255,0.15)',
      itemSelectedColor: COLORS.primary,
    },
    Notification: {
      colorBgElevated: COLORS.bgElevated,
    },
    Message: {
      contentBg: COLORS.bgElevated,
    },
  },
}
